apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: white
  namespace: sa-telemetry
spec:
  version: v2.3.2
  tag: latest
  baseImage: {{ registry_path }}/{{ imagestream_namespace }}/prometheus
  alerting:
    alert_relabel_configs:
    - regex: (.+)\d+
      source_labels: dc
      target_label: dc
    alertmanagers:
    - name: alertmanager
      namespace: sa-telemetry
      port: metrics
  podMetadata:
    labels:
      app: prometheus
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      role: sa-telemetry
  securityContext:
    nonroot: true
  serviceAccountName: prometheus-sa
  serviceMonitorSelector:
    matchLabels:
      app: smart-gateway
  storage:
    class: ""
    resources: {}
    selector: {}
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: {{ prometheus_pvc_storage_request }}
