apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: sa
spec:
  version: v0.15.0
  nodeSelector:
    application: sa-telemetry
    node-role.kubernetes.io/compute: "true"
  podAntiAffinity: hard
  podMetadata:
    labels:
      app: alertmanager
  replicas: 3
  securityContext:
    nonroot: true
