language: minimal
sudo: required

# 2019/12/12 - leifmadsen
# until there is an `oc cluster up` equivalent for OKD 4, we're stuck needing
# to disable CI until a work around is available
branches:
  only:
    - saf-ocp3

before_install:
- tests/install-and-run-ocp.sh

install:
- sudo add-apt-repository ppa:ansible/ansible-2.8 -y
- sudo apt-get update
- sudo apt-get install -y ansible openssl wget

script:
- cd deploy
- ./quickstart.sh
- cd ../tests/smoketest
- ./smoketest.sh
