apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: sa
spec:
  version: v0.15.0
  podMetadata:
    labels:
      app: alertmanager
  replicas: {{ alertmanager_replicas }}
  securityContext:
    nonroot: true
