---
apiVersion: "logging.openshift.io/v1"
kind: "Elasticsearch"
metadata:
  name: "elasticsearch"
spec:
  managementState: "Managed"
  nodeSpec:
    image: {{ registry_path }}/{{ imagestream_namespace }}/ose-elasticsearch5:latest
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
  nodes:
  - nodeCount: 1
    roles:
    - client
    - data
    - master
    storage: {}
  redundancyPolicy: ZeroRedundancy
