apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator-sa-telemetry
rules:
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - thirdpartyresources
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  attributeRestrictions: null
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  attributeRestrictions: null
  resources:
  - alertmanagers
  - alertmanagers/finalizers
  - prometheuses
  - prometheuses/finalizers
  - prometheusrules
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - apps
  attributeRestrictions: null
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - pods
  verbs:
  - delete
  - list
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - endpoints
  - services
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - namespaces
  verbs:
  - list
  - watch
