apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qdr-operator
subjects:
- kind: ServiceAccount
  namespace: sa-telemetry
  name: qdr-operator
roleRef:
  kind: ClusterRole
  name: qdr-operator
  apiGroup: rbac.authorization.k8s.io
