apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrouterd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: qdrouterd-operator
  template:
    metadata:
      labels:
        name: qdrouterd-operator
    spec:
      serviceAccountName: qdrouterd-operator
      containers:
        - name: qdrouterd-operator
          # Replace this with the built image name
          image: quay.io/interconnectedcloud/qdrouterd-operator:1.0.0-beta2
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - qdrouterd-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "qdrouterd-operator"
