apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Qdr
metadata:
  name: qdr-white
  namespace: sa-telemetry
spec:
  deploymentPlan:
      image: {{ registry_path }}/{{ imagestream_namespace }}/amq-interconnect:1.4-7
      role: interior
      size: 1
      placement: Any
  addresses:
    - prefix: closest
      distribution: closest
    - prefix: multicast
      distribution: multicast
    - prefix: unicast
      distribution: closest
    - prefix: exclusive
      distribution: closest
    - prefix: broadcast
      distribution: multicast
    - prefix: collectd/telemetry
      distribution: multicast
  sslProfiles:
    - name: default
      credentials: "qdr-white-cert"
  edgeListeners:
    - host: "0.0.0.0"
      port: 5671
      sslProfile: default
      expose: true
  listeners:
    - port: 5672
    - port: 8672
      http: true
