apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-gateway-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smart-gateway-operator
  template:
    metadata:
      labels:
        name: smart-gateway-operator
    spec:
      serviceAccountName: smart-gateway-operator
      containers:
        - name: smart-gateway-operator
          image: smart-gateway-operator
          imagePullPolicy: "Always"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "smart-gateway-operator"
