- name: Loop through templates
  template:
    src: "{{ item }}"
    dest: "{{ item }}"
  loop:
    - operators/prometheus/operator.yaml
    - operators/qdrouterd/operator.yaml
    - operators/smartgateway/operator.yaml
    - operators/elasticsearch/01-service-account.yaml
    - operators/elasticsearch/02-role.yaml
    - operators/elasticsearch/03-role-bindings.yaml
    - operators/elasticsearch/04-crd.yaml
    - operators/elasticsearch/05-deployment.yaml
    - service-assurance/prometheus/prometheus.yaml
    - service-assurance/alertmanager/alertmanager.yaml
    - service-assurance/qdrouterd/qdrouterd.yaml
    - service-assurance/smartgateway/metrics-smartgateway.yaml
    - service-assurance/smartgateway/events-smartgateway.yaml
    - service-assurance/elasticsearch/elasticsearch.yaml
