---
- src: oVirt.engine-setup
  version: 1.1.9
- src: oVirt.infra
  version: 1.1.12
- src: oVirt.image-template
  version: 1.1.9
- src: oVirt.repositories
  version: 1.1.5
- src: oVirt.vm-infra
  version: 1.1.15
- src: https://github.com/openshift/openshift-ansible
  name: openshift.openshift-ansible
  version: "openshift-ansible-3.11.114-1"
