apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Qdr
metadata:
  name: interior-interconnect
spec:
  # Add fields here
  deploymentPlan:
    image: quay.io/interconnectedcloud/qdrouterd:1.7.0
    role: interior
    size: 3
    placement: Any
  addresses:
    - prefix: balanced
      distribution: balanced
    - prefix: closest
      distribution: closest
    - prefix: multicast
      distribution: multicast
