all:
  hosts:
    manager:
      ansible_host: engine.dev7.nfvpe.site
      ansible_private_key_file: /home/lmadsen/.ssh/id_rsa
      ansible_user: root
      password_file: nfvha-lab.yml
  children:
    engine:
      hosts:
        manager:
      vars:
        vm_state: running
        wait_for_ip: yes
        vm_infra_wait_for_ip_retries: 20 # Higher than default to wait for all IPs on all VMs
        vm_infra_wait_for_ip_delay: 30


        engine_url: https://engine.dev7.nfvpe.site/ovirt-engine/api
        engine_user: admin@internal
        engine_cafile: /etc/pki/ovirt-engine/ca.pem

        openshift_infra:
          cluster: Default
          domain: dev7.nfvpe.site
          template: rhel76_template
          storage_domain: vmstore
          high_availability: true
          memory: 16GiB
          cores: 4
          state: "{{ vm_state }}"
          ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW5OI/o+gZm8k216iTbnkv5pJnGJfOJ8yMYrJ8c6pYia8ZwkUtFWj/3LzNWO2r/XiMCV9eOfUo8By1adb9WNgWH8fIhT3QwE60nX6HGilbW3EWVJF7WrHeodZJ4oFHzjGr/pmSsTL3lEbw/+ghHD1CrVMmNAuluaU7U9meY2S9iWAcI/5VMQBkyfqOA5uwMmDdBMVw+sS5oRrCKJ1sNqKosnRBmD7V6HvTgkxrmOgHzcxmU4jLN0rur4YCNJDUBZf+ZroHFDRJBwqu6QBqMxc+mzePwE/VAmhaf55Q8w15/Km+ilUcWgoZiYoqIWRLvfSqHbAWhCiqJW9av6YuY8aH lmadsen@rover.home.ljam.me

        openshift_master:
          cluster: Default
          domain: dev7.nfvpe.site
          template: rhel76_template
          storage_domain: vmstore
          high_availability: true
          memory: 24GiB
          cores: 6
          state: "{{ vm_state }}"
          ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW5OI/o+gZm8k216iTbnkv5pJnGJfOJ8yMYrJ8c6pYia8ZwkUtFWj/3LzNWO2r/XiMCV9eOfUo8By1adb9WNgWH8fIhT3QwE60nX6HGilbW3EWVJF7WrHeodZJ4oFHzjGr/pmSsTL3lEbw/+ghHD1CrVMmNAuluaU7U9meY2S9iWAcI/5VMQBkyfqOA5uwMmDdBMVw+sS5oRrCKJ1sNqKosnRBmD7V6HvTgkxrmOgHzcxmU4jLN0rur4YCNJDUBZf+ZroHFDRJBwqu6QBqMxc+mzePwE/VAmhaf55Q8w15/Km+ilUcWgoZiYoqIWRLvfSqHbAWhCiqJW9av6YuY8aH lmadsen@rover.home.ljam.me
          disks:
            - size: 40GiB
              name: data
              storage_domain: data
              interface: virtio
              format: cow

        openshift_node:
          cluster: Default
          domain: dev7.nfvpe.site
          template: rhel76_template
          storage_domain: vmstore
          high_availability: true
          memory: 32GiB
          cores: 4
          state: "{{ vm_state }}"
          ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW5OI/o+gZm8k216iTbnkv5pJnGJfOJ8yMYrJ8c6pYia8ZwkUtFWj/3LzNWO2r/XiMCV9eOfUo8By1adb9WNgWH8fIhT3QwE60nX6HGilbW3EWVJF7WrHeodZJ4oFHzjGr/pmSsTL3lEbw/+ghHD1CrVMmNAuluaU7U9meY2S9iWAcI/5VMQBkyfqOA5uwMmDdBMVw+sS5oRrCKJ1sNqKosnRBmD7V6HvTgkxrmOgHzcxmU4jLN0rur4YCNJDUBZf+ZroHFDRJBwqu6QBqMxc+mzePwE/VAmhaf55Q8w15/Km+ilUcWgoZiYoqIWRLvfSqHbAWhCiqJW9av6YuY8aH lmadsen@rover.home.ljam.me

        affinity_groups:
          - name: blue
            cluster: Default
            description: Blue affinity group
            host_rule: positive
            host_enforcing: true
            hosts:
              - nfvha-strg-01.oot.lab.eng.bos.redhat.com
            vm_rule: positive
            vm_enforcing: true
            vms:
              - openshift-master-1
              - openshift-compute-1
              - openshift-infra-node-1
          - name: green
            cluster: Default
            description: Green affinity group
            host_rule: positive
            host_enforcing: true
            hosts:
              - nfvha-strg-02.oot.lab.eng.bos.redhat.com
            vm_rule: positive
            vm_enforcing: true
            vms:
              - openshift-master-2
              - openshift-compute-2
              - openshift-infra-node-2
          - name: white
            cluster: Default
            description: White affinity group (neutral)
            host_rule: positive
            host_enforcing: true
            hosts:
              - nfvha-strg-03.oot.lab.eng.bos.redhat.com
            vm_rule: positive
            vm_enforcing: true
            vms:
              - openshift-lb
              - openshift-master-3
              - openshift-compute-3
              - openshift-infra-node-3

        vms:
          - name: openshift-lb
            tag: openshift_infra
            profile: "{{ openshift_infra }}"
            cloud_init:
              host_name: openshift-lb.dev7.nfvpe.site
              nic_ip_address: 10.19.110.100
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: dev7.nfvpe.site
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-master-1
            tag: openshift_master
            profile: "{{ openshift_master }}"
            cloud_init:
              host_name: openshift-master-1.dev7.nfvpe.site
              nic_ip_address: 10.19.110.101
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: dev7.nfvpe.site
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-master-2
            tag: openshift_master
            profile: "{{ openshift_master }}"
            cloud_init:
              host_name: openshift-master-2.dev7.nfvpe.site
              nic_ip_address: 10.19.110.102
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: dev7.nfvpe.site
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-master-3
            tag: openshift_master
            profile: "{{ openshift_master }}"
            cloud_init:
              host_name: openshift-master-3.dev7.nfvpe.site
              nic_ip_address: 10.19.110.103
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: dev7.nfvpe.site
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-compute-1
            tag: openshift_node
            profile: "{{ openshift_node }}"
            cloud_init:
              host_name: openshift-compute-1.dev7.nfvpe.site
              nic_ip_address: 10.19.110.104
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: dev7.nfvpe.site
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-compute-2
            tag: openshift_node
            profile: "{{ openshift_node }}"
            cloud_init:
              host_name: openshift-compute-2.dev7.nfvpe.site
              nic_ip_address: 10.19.110.105
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: dev7.nfvpe.site
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-compute-3
            tag: openshift_node
            profile: "{{ openshift_node }}"
            cloud_init:
              host_name: openshift-compute-3.dev7.nfvpe.site
              nic_ip_address: 10.19.110.106
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: dev7.nfvpe.site
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-infra-node-1
            tag: openshift_infra
            profile: "{{ openshift_infra }}"
            cloud_init:
              host_name: openshift-infra-node-1.dev7.nfvpe.site
              nic_ip_address: 10.19.110.107
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: dev7.nfvpe.site
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-infra-node-2
            tag: openshift_infra
            profile: "{{ openshift_infra }}"
            cloud_init:
              host_name: openshift-infra-node-2.dev7.nfvpe.site
              nic_ip_address: 10.19.110.108
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: dev7.nfvpe.site
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-infra-node-3
            tag: openshift_infra
            profile: "{{ openshift_infra }}"
            cloud_init:
              host_name: openshift-infra-node-3.dev7.nfvpe.site
              nic_ip_address: 10.19.110.109
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: dev7.nfvpe.site
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
# vim: set tabstop=2 shiftwidth=2 smartindent expandtab :
