all:
  hosts:
    manager:
      ansible_host: engine.rhhi-v.tld
      ansible_private_key_file: /home/bastion_user/.ssh/id_rsa
      ansible_user: root
      password_file: rhsubs.yml
  children:
    engine:
      hosts:
        manager:
      vars:
        vm_state: running
        wait_for_ip: yes
        vm_infra_wait_for_ip_retries: 20 # Higher than default to wait for all IPs on all VMs
        vm_infra_wait_for_ip_delay: 30


        engine_url: https://engine.rhhi-v.tld/ovirt-engine/api
        engine_user: admin@internal
        engine_cafile: /etc/pki/ovirt-engine/ca.pem

        openshift_infra:
          cluster: Default
          domain: service-assurance.tld
          template: rhel76_template
          storage_domain: vmstore
          high_availability: true
          memory: 16GiB
          cores: 4
          state: "{{ vm_state }}"
          ssh_key: ssh-rsa AAAA...ZZZZ bastion@jumphost

        openshift_master:
          cluster: Default
          domain: service-assurance.tld
          template: rhel76_template
          storage_domain: vmstore
          high_availability: true
          memory: 24GiB
          cores: 6
          state: "{{ vm_state }}"
          ssh_key: ssh-rsa AAAA...ZZZZ bastion@jumphost
          disks:
            - size: 40GiB
              name: data
              storage_domain: data
              interface: virtio
              format: cow

        openshift_node:
          cluster: Default
          domain: service-assurance.tld
          template: rhel76_template
          storage_domain: vmstore
          high_availability: true
          memory: 32GiB
          cores: 4
          state: "{{ vm_state }}"
          ssh_key: ssh-rsa AAAA...ZZZZ bastion@jumphost

        affinity_groups:
          - name: blue
            cluster: Default
            description: Blue affinity group
            host_rule: positive
            host_enforcing: true
            hosts:
              - nfvha-strg-01.oot.lab.eng.bos.redhat.com
            vm_rule: positive
            vm_enforcing: true
            vms:
              - openshift-master-1
              - openshift-compute-1
              - openshift-infra-node-1
          - name: green
            cluster: Default
            description: Green affinity group
            host_rule: positive
            host_enforcing: true
            hosts:
              - nfvha-strg-02.oot.lab.eng.bos.redhat.com
            vm_rule: positive
            vm_enforcing: true
            vms:
              - openshift-master-2
              - openshift-compute-2
              - openshift-infra-node-2
          - name: white
            cluster: Default
            description: White affinity group (neutral)
            host_rule: positive
            host_enforcing: true
            hosts:
              - nfvha-strg-03.oot.lab.eng.bos.redhat.com
            vm_rule: positive
            vm_enforcing: true
            vms:
              - openshift-lb
              - openshift-master-3
              - openshift-compute-3
              - openshift-infra-node-3

        vms:
          - name: openshift-lb
            tag: openshift_infra
            profile: "{{ openshift_infra }}"
            cloud_init:
              host_name: openshift-lb.service-assurance.tld
              nic_ip_address: 10.19.110.100
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: service-assurance.tld
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-master-1
            tag: openshift_master
            profile: "{{ openshift_master }}"
            cloud_init:
              host_name: openshift-master-1.service-assurance.tld
              nic_ip_address: 10.19.110.101
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: service-assurance.tld
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-master-2
            tag: openshift_master
            profile: "{{ openshift_master }}"
            cloud_init:
              host_name: openshift-master-2.service-assurance.tld
              nic_ip_address: 10.19.110.102
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: service-assurance.tld
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-master-3
            tag: openshift_master
            profile: "{{ openshift_master }}"
            cloud_init:
              host_name: openshift-master-3.service-assurance.tld
              nic_ip_address: 10.19.110.103
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: service-assurance.tld
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-compute-1
            tag: openshift_node
            profile: "{{ openshift_node }}"
            cloud_init:
              host_name: openshift-compute-1.service-assurance.tld
              nic_ip_address: 10.19.110.104
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: service-assurance.tld
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-compute-2
            tag: openshift_node
            profile: "{{ openshift_node }}"
            cloud_init:
              host_name: openshift-compute-2.service-assurance.tld
              nic_ip_address: 10.19.110.105
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: service-assurance.tld
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-compute-3
            tag: openshift_node
            profile: "{{ openshift_node }}"
            cloud_init:
              host_name: openshift-compute-3.service-assurance.tld
              nic_ip_address: 10.19.110.106
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: service-assurance.tld
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-infra-node-1
            tag: openshift_infra
            profile: "{{ openshift_infra }}"
            cloud_init:
              host_name: openshift-infra-node-1.service-assurance.tld
              nic_ip_address: 10.19.110.107
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: service-assurance.tld
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-infra-node-2
            tag: openshift_infra
            profile: "{{ openshift_infra }}"
            cloud_init:
              host_name: openshift-infra-node-2.service-assurance.tld
              nic_ip_address: 10.19.110.108
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: service-assurance.tld
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
          - name: openshift-infra-node-3
            tag: openshift_infra
            profile: "{{ openshift_infra }}"
            cloud_init:
              host_name: openshift-infra-node-3.service-assurance.tld
              nic_ip_address: 10.19.110.109
              root_password: redhat
              dns_servers: 10.19.110.3
              dns_search: service-assurance.tld
              nic_boot_protocol: static
              nic_netmask: 255.255.255.0
              nic_gateway: 10.19.110.254
              nic_on_boot: true
              nic_name: eth0
